export const FILTER_OPTIONS = [
  {
    label: '최신순',
    value: 'latest',
  },
  {
    label: '인기순',
    value: 'popular',
  },
];

export type DevelopOccupationType = {
  id: number;
  occupation: string;
};

export type DevelopSkillType = {
  id: number;
  skill: string;
};

export const DEVELOP_OCCUPATIONS = [
  { id: 0, occupation: '프론트엔드 개발자' },
  { id: 1, occupation: '백엔드 개발자' },
  { id: 2, occupation: '풀스택 개발자' },
  { id: 3, occupation: '웹 개발자' },
  { id: 4, occupation: '모바일 앱 개발자' },
  { id: 5, occupation: 'iOS 개발자' },
  { id: 6, occupation: '안드로이드 개발자' },
  { id: 7, occupation: '임베디드 개발자' },
  { id: 8, occupation: '게임 개발자' },
  { id: 9, occupation: 'AI 엔지니어' },
  { id: 10, occupation: '데이터 엔지니어' },
  { id: 11, occupation: '데이터 사이언티스트' },
  { id: 12, occupation: '머신러닝 엔지니어' },
  { id: 13, occupation: '딥러닝 엔지니어' },
  { id: 14, occupation: 'DevOps 엔지니어' },
  { id: 15, occupation: '클라우드 엔지니어' },
  { id: 16, occupation: '보안 엔지니어' },
  { id: 17, occupation: 'QA 엔지니어' },
  { id: 18, occupation: '테스트 자동화 엔지니어' },
  { id: 19, occupation: '소프트웨어 엔지니어' },
  { id: 20, occupation: '시스템 엔지니어' },
  { id: 21, occupation: '네트워크 엔지니어' },
  { id: 22, occupation: 'DBA (데이터베이스 관리자)' },
  { id: 23, occupation: '크로스플랫폼 앱 개발자' },
  { id: 24, occupation: 'VR/AR 개발자' },
  { id: 25, occupation: '로보틱스 엔지니어' },
  { id: 26, occupation: '블록체인 개발자' },
  { id: 27, occupation: '스크럼 마스터' },
  { id: 28, occupation: '기술 리드' },
];

export const DEVELOP_SKILLS = [
  { id: 1, skill: 'JavaScript' },
  { id: 2, skill: 'TypeScript' },
  { id: 3, skill: 'Python' },
  { id: 4, skill: 'Java' },
  { id: 5, skill: 'Kotlin' },
  { id: 6, skill: 'C' },
  { id: 7, skill: 'C++' },
  { id: 8, skill: 'C#' },
  { id: 9, skill: 'Go' },
  { id: 10, skill: 'Rust' },
  { id: 11, skill: 'Ruby' },
  { id: 12, skill: 'PHP' },
  { id: 13, skill: 'Swift' },
  { id: 14, skill: 'Objective-C' },
  { id: 15, skill: 'Scala' },
  { id: 16, skill: 'Dart' },
  { id: 17, skill: 'Perl' },
  { id: 18, skill: 'Haskell' },
  { id: 19, skill: 'Elixir' },
  { id: 20, skill: 'R' },
  { id: 21, skill: 'HTML' },
  { id: 22, skill: 'CSS' },
  { id: 23, skill: 'Sass' },
  { id: 24, skill: 'Less' },
  { id: 25, skill: 'SQL' },
  { id: 26, skill: 'GraphQL' },
  { id: 27, skill: 'NoSQL' },
  { id: 28, skill: 'MongoDB' },
  { id: 29, skill: 'PostgreSQL' },
  { id: 30, skill: 'MySQL' },
  { id: 31, skill: 'MariaDB' },
  { id: 32, skill: 'Redis' },
  { id: 33, skill: 'SQLite' },
  { id: 34, skill: 'Firebase' },
  { id: 35, skill: 'DynamoDB' },
  { id: 36, skill: 'Oracle' },
  { id: 37, skill: 'Express' },
  { id: 38, skill: 'NestJS' },
  { id: 39, skill: 'Next.js' },
  { id: 40, skill: 'Nuxt.js' },
  { id: 41, skill: 'React' },
  { id: 42, skill: 'Redux' },
  { id: 43, skill: 'Recoil' },
  { id: 44, skill: 'Vue.js' },
  { id: 45, skill: 'Vuex' },
  { id: 46, skill: 'Pinia' },
  { id: 47, skill: 'Angular' },
  { id: 48, skill: 'Svelte' },
  { id: 49, skill: 'jQuery' },
  { id: 50, skill: 'Bootstrap' },
  { id: 51, skill: 'Tailwind CSS' },
  { id: 52, skill: 'Node.js' },
  { id: 53, skill: 'Deno' },
  { id: 54, skill: 'Bun' },
  { id: 55, skill: 'Spring' },
  { id: 56, skill: 'Spring Boot' },
  { id: 57, skill: 'Micronaut' },
  { id: 58, skill: 'Flask' },
  { id: 59, skill: 'Django' },
  { id: 60, skill: 'FastAPI' },
  { id: 61, skill: 'Tornado' },
  { id: 62, skill: 'Rails' },
  { id: 63, skill: 'Sinatra' },
  { id: 64, skill: 'Laravel' },
  { id: 65, skill: 'Symfony' },
  { id: 66, skill: 'ASP.NET' },
  { id: 67, skill: 'Blazor' },
  { id: 68, skill: 'Unity' },
  { id: 69, skill: 'Unreal Engine' },
  { id: 70, skill: 'TensorFlow' },
  { id: 71, skill: 'PyTorch' },
  { id: 72, skill: 'Keras' },
  { id: 73, skill: 'OpenCV' },
  { id: 74, skill: 'Pandas' },
  { id: 75, skill: 'NumPy' },
  { id: 76, skill: 'Matplotlib' },
  { id: 77, skill: 'Scikit-learn' },
  { id: 78, skill: 'Jupyter' },
  { id: 79, skill: 'VS Code' },
  { id: 80, skill: 'WebStorm' },
  { id: 81, skill: 'Eclipse' },
  { id: 82, skill: 'IntelliJ IDEA' },
  { id: 83, skill: 'Android Studio' },
  { id: 84, skill: 'Xcode' },
  { id: 85, skill: 'Git' },
  { id: 86, skill: 'GitHub' },
  { id: 87, skill: 'GitLab' },
  { id: 88, skill: 'Bitbucket' },
  { id: 89, skill: 'Docker' },
  { id: 90, skill: 'Kubernetes' },
  { id: 91, skill: 'Terraform' },
  { id: 92, skill: 'Ansible' },
  { id: 93, skill: 'Jenkins' },
  { id: 94, skill: 'Travis CI' },
  { id: 95, skill: 'CircleCI' },
  { id: 96, skill: 'GitHub Actions' },
  { id: 97, skill: 'AWS' },
  { id: 98, skill: 'GCP' },
  { id: 99, skill: 'Azure' },
  { id: 100, skill: 'Vercel' },
  { id: 101, skill: 'Netlify' },
  { id: 102, skill: 'Heroku' },
  { id: 103, skill: 'DigitalOcean' },
  { id: 104, skill: 'Slack' },
  { id: 105, skill: 'Notion' },
  { id: 106, skill: 'Trello' },
  { id: 107, skill: 'Figma' },
  { id: 108, skill: 'Postman' },
  { id: 109, skill: 'Insomnia' },
  { id: 110, skill: 'Chrome DevTools' },
  { id: 111, skill: 'WebSocket' },
  { id: 112, skill: 'REST API' },
  { id: 113, skill: 'gRPC' },
  { id: 114, skill: 'GraphQL API' },
  { id: 115, skill: 'OAuth2' },
  { id: 116, skill: 'JWT' },
  { id: 117, skill: 'OpenAPI' },
  { id: 118, skill: 'Linux' },
  { id: 119, skill: 'Ubuntu' },
  { id: 120, skill: 'Windows' },
  { id: 121, skill: 'macOS' },
  { id: 122, skill: 'Nginx' },
  { id: 123, skill: 'Apache' },
  { id: 124, skill: 'Tomcat' },
  { id: 125, skill: 'Webpack' },
  { id: 126, skill: 'Vite' },
  { id: 127, skill: 'Rollup' },
  { id: 128, skill: 'Parcel' },
  { id: 129, skill: 'ESLint' },
  { id: 130, skill: 'Prettier' },
  { id: 131, skill: 'Babel' },
  { id: 132, skill: 'TypeORM' },
  { id: 133, skill: 'Prisma' },
  { id: 134, skill: 'Mongoose' },
  { id: 135, skill: 'Sequelize' },
  { id: 136, skill: 'Jest' },
  { id: 137, skill: 'Mocha' },
  { id: 138, skill: 'Chai' },
  { id: 139, skill: 'Cypress' },
  { id: 140, skill: 'Playwright' },
  { id: 141, skill: 'Vitest' },
  { id: 142, skill: 'Storybook' },
  { id: 143, skill: 'Zustand' },
  { id: 144, skill: 'Jotai' },
  { id: 145, skill: 'TanStack Query' },
  { id: 146, skill: 'Three.js' },
  { id: 147, skill: 'React Native' },
  { id: 148, skill: 'Expo' },
  { id: 149, skill: 'Electron' },
  { id: 150, skill: 'Capacitor' },
  { id: 151, skill: 'Cordova' },
  { id: 152, skill: 'OpenGL' },
  { id: 153, skill: 'Vulkan' },
  { id: 154, skill: 'Memcached' },
  { id: 155, skill: 'Elasticsearch' },
  { id: 156, skill: 'Algolia' },
  { id: 157, skill: 'Meilisearch' },
  { id: 158, skill: 'RabbitMQ' },
  { id: 159, skill: 'Kafka' },
  { id: 160, skill: 'MQTT' },
];
