export const SKILL_CATEGORIES = [
  { id: 1, name: 'JavaScript' },
  { id: 2, name: 'TypeScript' },
  { id: 3, name: 'Python' },
  { id: 4, name: 'Java' },
  { id: 5, name: 'Kotlin' },
  { id: 6, name: 'C' },
  { id: 7, name: 'C++' },
  { id: 8, name: 'C#' },
  { id: 9, name: 'Go' },
  { id: 10, name: 'Rust' },
  { id: 11, name: 'Ruby' },
  { id: 12, name: 'PHP' },
  { id: 13, name: 'Swift' },
  { id: 14, name: 'Objective-C' },
  { id: 15, name: 'Scala' },
  { id: 16, name: 'Dart' },
  { id: 17, name: 'Perl' },
  { id: 18, name: 'Haskell' },
  { id: 19, name: 'Elixir' },
  { id: 20, name: 'R' },
  { id: 21, name: 'HTML' },
  { id: 22, name: 'CSS' },
  { id: 23, name: 'Sass' },
  { id: 24, name: 'Less' },
  { id: 25, name: 'SQL' },
  { id: 26, name: 'GraphQL' },
  { id: 27, name: 'NoSQL' },
  { id: 28, name: 'MongoDB' },
  { id: 29, name: 'PostgreSQL' },
  { id: 30, name: 'MySQL' },
  { id: 31, name: 'MariaDB' },
  { id: 32, name: 'Redis' },
  { id: 33, name: 'SQLite' },
  { id: 34, name: 'Firebase' },
  { id: 35, name: 'DynamoDB' },
  { id: 36, name: 'Oracle' },
  { id: 37, name: 'Express' },
  { id: 38, name: 'NestJS' },
  { id: 39, name: 'Next.js' },
  { id: 40, name: 'Nuxt.js' },
  { id: 41, name: 'React' },
  { id: 42, name: 'Redux' },
  { id: 43, name: 'Recoil' },
  { id: 44, name: 'Vue.js' },
  { id: 45, name: 'Vuex' },
  { id: 46, name: 'Pinia' },
  { id: 47, name: 'Angular' },
  { id: 48, name: 'Svelte' },
  { id: 49, name: 'jQuery' },
  { id: 50, name: 'Bootstrap' },
  { id: 51, name: 'Tailwind CSS' },
  { id: 52, name: 'Node.js' },
  { id: 53, name: 'Deno' },
  { id: 54, name: 'Bun' },
  { id: 55, name: 'Spring' },
  { id: 56, name: 'Spring Boot' },
  { id: 57, name: 'Micronaut' },
  { id: 58, name: 'Flask' },
  { id: 59, name: 'Django' },
  { id: 60, name: 'FastAPI' },
  { id: 61, name: 'Tornado' },
  { id: 62, name: 'Rails' },
  { id: 63, name: 'Sinatra' },
  { id: 64, name: 'Laravel' },
  { id: 65, name: 'Symfony' },
  { id: 66, name: 'ASP.NET' },
  { id: 67, name: 'Blazor' },
  { id: 68, name: 'Unity' },
  { id: 69, name: 'Unreal Engine' },
  { id: 70, name: 'TensorFlow' },
  { id: 71, name: 'PyTorch' },
  { id: 72, name: 'Keras' },
  { id: 73, name: 'OpenCV' },
  { id: 74, name: 'Pandas' },
  { id: 75, name: 'NumPy' },
  { id: 76, name: 'Matplotlib' },
  { id: 77, name: 'Scikit-learn' },
  { id: 78, name: 'Jupyter' },
  { id: 79, name: 'VS Code' },
  { id: 80, name: 'WebStorm' },
  { id: 81, name: 'Eclipse' },
  { id: 82, name: 'IntelliJ IDEA' },
  { id: 83, name: 'Android Studio' },
  { id: 84, name: 'Xcode' },
  { id: 85, name: 'Git' },
  { id: 86, name: 'GitHub' },
  { id: 87, name: 'GitLab' },
  { id: 88, name: 'Bitbucket' },
  { id: 89, name: 'Docker' },
  { id: 90, name: 'Kubernetes' },
  { id: 91, name: 'Terraform' },
  { id: 92, name: 'Ansible' },
  { id: 93, name: 'Jenkins' },
  { id: 94, name: 'Travis CI' },
  { id: 95, name: 'CircleCI' },
  { id: 96, name: 'GitHub Actions' },
  { id: 97, name: 'AWS' },
  { id: 98, name: 'GCP' },
  { id: 99, name: 'Azure' },
  { id: 100, name: 'Vercel' },
  { id: 101, name: 'Netlify' },
  { id: 102, name: 'Heroku' },
  { id: 103, name: 'DigitalOcean' },
  { id: 104, name: 'Slack' },
  { id: 105, name: 'Notion' },
  { id: 106, name: 'Trello' },
  { id: 107, name: 'Figma' },
  { id: 108, name: 'Postman' },
  { id: 109, name: 'Insomnia' },
  { id: 110, name: 'Chrome DevTools' },
  { id: 111, name: 'WebSocket' },
  { id: 112, name: 'REST API' },
  { id: 113, name: 'gRPC' },
  { id: 114, name: 'GraphQL API' },
  { id: 115, name: 'OAuth2' },
  { id: 116, name: 'JWT' },
  { id: 117, name: 'OpenAPI' },
  { id: 118, name: 'Linux' },
  { id: 119, name: 'Ubuntu' },
  { id: 120, name: 'Windows' },
  { id: 121, name: 'macOS' },
  { id: 122, name: 'Nginx' },
  { id: 123, name: 'Apache' },
  { id: 124, name: 'Tomcat' },
  { id: 125, name: 'Webpack' },
  { id: 126, name: 'Vite' },
  { id: 127, name: 'Rollup' },
  { id: 128, name: 'Parcel' },
  { id: 129, name: 'ESLint' },
  { id: 130, name: 'Prettier' },
  { id: 131, name: 'Babel' },
  { id: 132, name: 'TypeORM' },
  { id: 133, name: 'Prisma' },
  { id: 134, name: 'Mongoose' },
  { id: 135, name: 'Sequelize' },
  { id: 136, name: 'Jest' },
  { id: 137, name: 'Mocha' },
  { id: 138, name: 'Chai' },
  { id: 139, name: 'Cypress' },
  { id: 140, name: 'Playwright' },
  { id: 141, name: 'Vitest' },
  { id: 142, name: 'Storybook' },
  { id: 143, name: 'Zustand' },
  { id: 144, name: 'Jotai' },
  { id: 145, name: 'TanStack Query' },
  { id: 146, name: 'Three.js' },
  { id: 147, name: 'React Native' },
  { id: 148, name: 'Expo' },
  { id: 149, name: 'Electron' },
  { id: 150, name: 'Capacitor' },
  { id: 151, name: 'Cordova' },
  { id: 152, name: 'OpenGL' },
  { id: 153, name: 'Vulkan' },
  { id: 154, name: 'Memcached' },
  { id: 155, name: 'Elasticsearch' },
  { id: 156, name: 'Algolia' },
  { id: 157, name: 'Meilisearch' },
  { id: 158, name: 'RabbitMQ' },
  { id: 159, name: 'Kafka' },
  { id: 160, name: 'MQTT' },
];

export const PROJECT_STATUS_OPTIONS = [
  { label: '진행중인 상태', value: 'IN_PROGRESS' },
  { label: '완료된 상태', value: 'COMPLETED' },
  { label: '보류된 상태', value: 'ON_HOLD' },
];

export type ProjectDetailType = {
  id: string;
  createdAt: string;
  endDate: string;
  isPublic: boolean;
  projectDesc: string;
  projectName: string;
  projectNumber: number;
  role: string;
  skill: {
    customSkills: string[];
    generalSkills: string[];
  };
  startDate: string;
  status: string;
  tags: string[];
  updatedAt: string;
};
