export const skillList = [
  { id: 0, value: 'JavaScript' },
  { id: 1, value: 'TypeScript' },
  { id: 2, value: 'React' },
  { id: 3, value: 'Next.js' },
  { id: 4, value: 'Vue.js' },
  { id: 5, value: 'Node.js' },
  { id: 6, value: 'Express' },
  { id: 7, value: 'HTML' },
  { id: 8, value: 'CSS' },
  { id: 9, value: 'Sass' },
  { id: 10, value: 'Tailwind CSS' },
  { id: 11, value: 'Redux' },
  { id: 12, value: 'Zustand' },
  { id: 13, value: 'React Query' },
  { id: 14, value: 'GraphQL' },
  { id: 15, value: 'Apollo' },
  { id: 16, value: 'Firebase' },
  { id: 17, value: 'MongoDB' },
  { id: 18, value: 'MySQL' },
  { id: 19, value: 'PostgreSQL' },
  { id: 20, value: 'Docker' },
  { id: 21, value: 'AWS' },
  { id: 22, value: 'Git' },
  { id: 23, value: 'Jest' },
  { id: 24, value: 'Cypress' },
  { id: 25, value: 'Python' },
  { id: 26, value: 'Java' },
  { id: 27, value: 'C#' },
  { id: 28, value: 'Kotlin' },
  { id: 29, value: 'Swift' },
];
